/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.dto;

import com.innovati.felipehernandez.invenenvios.clases.dao.*;
import com.innovati.felipehernandez.invenenvios.clases.factory.*;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Pedidos implements Serializable
{
	/** 
	 * This attribute maps to the column IdPedido in the Pedidos table.
	 */
	protected String idPedido;

	/** 
	 * This attribute represents whether the attribute idPedido has been modified since being read from the database.
	 */
	protected boolean idPedidoModified = false;

	/** 
	 * This attribute maps to the column IdUsuario in the Pedidos table.
	 */
	protected String idUsuario;

	/** 
	 * This attribute represents whether the attribute idUsuario has been modified since being read from the database.
	 */
	protected boolean idUsuarioModified = false;

	/** 
	 * This attribute maps to the column Folio in the Pedidos table.
	 */
	protected int folio;

	/** 
	 * This attribute represents whether the primitive attribute folio is null.
	 */
	protected boolean folioNull = true;

	/** 
	 * This attribute represents whether the attribute folio has been modified since being read from the database.
	 */
	protected boolean folioModified = false;

	/** 
	 * This attribute maps to the column ClaveCliente in the Pedidos table.
	 */
	protected String claveCliente;

	/** 
	 * This attribute represents whether the attribute claveCliente has been modified since being read from the database.
	 */
	protected boolean claveClienteModified = false;

	/** 
	 * This attribute maps to the column Fecha in the Pedidos table.
	 */
	protected Date fecha;

	/** 
	 * This attribute represents whether the attribute fecha has been modified since being read from the database.
	 */
	protected boolean fechaModified = false;

	/** 
	 * This attribute maps to the column Estatus in the Pedidos table.
	 */
	protected short estatus;

	/** 
	 * This attribute represents whether the primitive attribute estatus is null.
	 */
	protected boolean estatusNull = true;

	/** 
	 * This attribute represents whether the attribute estatus has been modified since being read from the database.
	 */
	protected boolean estatusModified = false;

	/** 
	 * This attribute maps to the column Subtotal in the Pedidos table.
	 */
	protected float subtotal;

	/** 
	 * This attribute represents whether the primitive attribute subtotal is null.
	 */
	protected boolean subtotalNull = true;

	/** 
	 * This attribute represents whether the attribute subtotal has been modified since being read from the database.
	 */
	protected boolean subtotalModified = false;

	/** 
	 * This attribute maps to the column IVA in the Pedidos table.
	 */
	protected float iva;

	/** 
	 * This attribute represents whether the primitive attribute iva is null.
	 */
	protected boolean ivaNull = true;

	/** 
	 * This attribute represents whether the attribute iva has been modified since being read from the database.
	 */
	protected boolean ivaModified = false;

	/** 
	 * This attribute maps to the column Total in the Pedidos table.
	 */
	protected float total;

	/** 
	 * This attribute represents whether the primitive attribute total is null.
	 */
	protected boolean totalNull = true;

	/** 
	 * This attribute represents whether the attribute total has been modified since being read from the database.
	 */
	protected boolean totalModified = false;

	/** 
	 * This attribute maps to the column Observaciones in the Pedidos table.
	 */
	protected String observaciones;

	/** 
	 * This attribute represents whether the attribute observaciones has been modified since being read from the database.
	 */
	protected boolean observacionesModified = false;

	/** 
	 * This attribute maps to the column UltimaFechaActualizacion in the Pedidos table.
	 */
	protected Date ultimaFechaActualizacion;

	/** 
	 * This attribute represents whether the attribute ultimaFechaActualizacion has been modified since being read from the database.
	 */
	protected boolean ultimaFechaActualizacionModified = false;

	/** 
	 * This attribute maps to the column UltimoUsuarioActualizacion in the Pedidos table.
	 */
	protected String ultimoUsuarioActualizacion;

	/** 
	 * This attribute represents whether the attribute ultimoUsuarioActualizacion has been modified since being read from the database.
	 */
	protected boolean ultimoUsuarioActualizacionModified = false;

	/**
	 * Method 'Pedidos'
	 * 
	 */
	public Pedidos()
	{
	}

	/**
	 * Method 'getIdPedido'
	 * 
	 * @return String
	 */
	public String getIdPedido()
	{
		return idPedido;
	}

	/**
	 * Method 'setIdPedido'
	 * 
	 * @param idPedido
	 */
	public void setIdPedido(String idPedido)
	{
		this.idPedido = idPedido;
		this.idPedidoModified = true;
	}

	/** 
	 * Sets the value of idPedidoModified
	 */
	public void setIdPedidoModified(boolean idPedidoModified)
	{
		this.idPedidoModified = idPedidoModified;
	}

	/** 
	 * Gets the value of idPedidoModified
	 */
	public boolean isIdPedidoModified()
	{
		return idPedidoModified;
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return String
	 */
	public String getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(String idUsuario)
	{
		this.idUsuario = idUsuario;
		this.idUsuarioModified = true;
	}

	/** 
	 * Sets the value of idUsuarioModified
	 */
	public void setIdUsuarioModified(boolean idUsuarioModified)
	{
		this.idUsuarioModified = idUsuarioModified;
	}

	/** 
	 * Gets the value of idUsuarioModified
	 */
	public boolean isIdUsuarioModified()
	{
		return idUsuarioModified;
	}

	/**
	 * Method 'getFolio'
	 * 
	 * @return int
	 */
	public int getFolio()
	{
		return folio;
	}

	/**
	 * Method 'setFolio'
	 * 
	 * @param folio
	 */
	public void setFolio(int folio)
	{
		this.folio = folio;
		this.folioNull = false;
		this.folioModified = true;
	}

	/**
	 * Method 'setFolioNull'
	 * 
	 * @param value
	 */
	public void setFolioNull(boolean value)
	{
		this.folioNull = value;
		this.folioModified = true;
	}

	/**
	 * Method 'isFolioNull'
	 * 
	 * @return boolean
	 */
	public boolean isFolioNull()
	{
		return folioNull;
	}

	/** 
	 * Sets the value of folioModified
	 */
	public void setFolioModified(boolean folioModified)
	{
		this.folioModified = folioModified;
	}

	/** 
	 * Gets the value of folioModified
	 */
	public boolean isFolioModified()
	{
		return folioModified;
	}

	/**
	 * Method 'getClaveCliente'
	 * 
	 * @return String
	 */
	public String getClaveCliente()
	{
		return claveCliente;
	}

	/**
	 * Method 'setClaveCliente'
	 * 
	 * @param claveCliente
	 */
	public void setClaveCliente(String claveCliente)
	{
		this.claveCliente = claveCliente;
		this.claveClienteModified = true;
	}

	/** 
	 * Sets the value of claveClienteModified
	 */
	public void setClaveClienteModified(boolean claveClienteModified)
	{
		this.claveClienteModified = claveClienteModified;
	}

	/** 
	 * Gets the value of claveClienteModified
	 */
	public boolean isClaveClienteModified()
	{
		return claveClienteModified;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
		this.fechaModified = true;
	}

	/** 
	 * Sets the value of fechaModified
	 */
	public void setFechaModified(boolean fechaModified)
	{
		this.fechaModified = fechaModified;
	}

	/** 
	 * Gets the value of fechaModified
	 */
	public boolean isFechaModified()
	{
		return fechaModified;
	}

	/**
	 * Method 'getEstatus'
	 * 
	 * @return short
	 */
	public short getEstatus()
	{
		return estatus;
	}

	/**
	 * Method 'setEstatus'
	 * 
	 * @param estatus
	 */
	public void setEstatus(short estatus)
	{
		this.estatus = estatus;
		this.estatusNull = false;
		this.estatusModified = true;
	}

	/**
	 * Method 'setEstatusNull'
	 * 
	 * @param value
	 */
	public void setEstatusNull(boolean value)
	{
		this.estatusNull = value;
		this.estatusModified = true;
	}

	/**
	 * Method 'isEstatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isEstatusNull()
	{
		return estatusNull;
	}

	/** 
	 * Sets the value of estatusModified
	 */
	public void setEstatusModified(boolean estatusModified)
	{
		this.estatusModified = estatusModified;
	}

	/** 
	 * Gets the value of estatusModified
	 */
	public boolean isEstatusModified()
	{
		return estatusModified;
	}

	/**
	 * Method 'getSubtotal'
	 * 
	 * @return float
	 */
	public float getSubtotal()
	{
		return subtotal;
	}

	/**
	 * Method 'setSubtotal'
	 * 
	 * @param subtotal
	 */
	public void setSubtotal(float subtotal)
	{
		this.subtotal = subtotal;
		this.subtotalNull = false;
		this.subtotalModified = true;
	}

	/**
	 * Method 'setSubtotalNull'
	 * 
	 * @param value
	 */
	public void setSubtotalNull(boolean value)
	{
		this.subtotalNull = value;
		this.subtotalModified = true;
	}

	/**
	 * Method 'isSubtotalNull'
	 * 
	 * @return boolean
	 */
	public boolean isSubtotalNull()
	{
		return subtotalNull;
	}

	/** 
	 * Sets the value of subtotalModified
	 */
	public void setSubtotalModified(boolean subtotalModified)
	{
		this.subtotalModified = subtotalModified;
	}

	/** 
	 * Gets the value of subtotalModified
	 */
	public boolean isSubtotalModified()
	{
		return subtotalModified;
	}

	/**
	 * Method 'getIva'
	 * 
	 * @return float
	 */
	public float getIva()
	{
		return iva;
	}

	/**
	 * Method 'setIva'
	 * 
	 * @param iva
	 */
	public void setIva(float iva)
	{
		this.iva = iva;
		this.ivaNull = false;
		this.ivaModified = true;
	}

	/**
	 * Method 'setIvaNull'
	 * 
	 * @param value
	 */
	public void setIvaNull(boolean value)
	{
		this.ivaNull = value;
		this.ivaModified = true;
	}

	/**
	 * Method 'isIvaNull'
	 * 
	 * @return boolean
	 */
	public boolean isIvaNull()
	{
		return ivaNull;
	}

	/** 
	 * Sets the value of ivaModified
	 */
	public void setIvaModified(boolean ivaModified)
	{
		this.ivaModified = ivaModified;
	}

	/** 
	 * Gets the value of ivaModified
	 */
	public boolean isIvaModified()
	{
		return ivaModified;
	}

	/**
	 * Method 'getTotal'
	 * 
	 * @return float
	 */
	public float getTotal()
	{
		return total;
	}

	/**
	 * Method 'setTotal'
	 * 
	 * @param total
	 */
	public void setTotal(float total)
	{
		this.total = total;
		this.totalNull = false;
		this.totalModified = true;
	}

	/**
	 * Method 'setTotalNull'
	 * 
	 * @param value
	 */
	public void setTotalNull(boolean value)
	{
		this.totalNull = value;
		this.totalModified = true;
	}

	/**
	 * Method 'isTotalNull'
	 * 
	 * @return boolean
	 */
	public boolean isTotalNull()
	{
		return totalNull;
	}

	/** 
	 * Sets the value of totalModified
	 */
	public void setTotalModified(boolean totalModified)
	{
		this.totalModified = totalModified;
	}

	/** 
	 * Gets the value of totalModified
	 */
	public boolean isTotalModified()
	{
		return totalModified;
	}

	/**
	 * Method 'getObservaciones'
	 * 
	 * @return String
	 */
	public String getObservaciones()
	{
		return observaciones;
	}

	/**
	 * Method 'setObservaciones'
	 * 
	 * @param observaciones
	 */
	public void setObservaciones(String observaciones)
	{
		this.observaciones = observaciones;
		this.observacionesModified = true;
	}

	/** 
	 * Sets the value of observacionesModified
	 */
	public void setObservacionesModified(boolean observacionesModified)
	{
		this.observacionesModified = observacionesModified;
	}

	/** 
	 * Gets the value of observacionesModified
	 */
	public boolean isObservacionesModified()
	{
		return observacionesModified;
	}

	/**
	 * Method 'getUltimaFechaActualizacion'
	 * 
	 * @return Date
	 */
	public Date getUltimaFechaActualizacion()
	{
		return ultimaFechaActualizacion;
	}

	/**
	 * Method 'setUltimaFechaActualizacion'
	 * 
	 * @param ultimaFechaActualizacion
	 */
	public void setUltimaFechaActualizacion(Date ultimaFechaActualizacion)
	{
		this.ultimaFechaActualizacion = ultimaFechaActualizacion;
		this.ultimaFechaActualizacionModified = true;
	}

	/** 
	 * Sets the value of ultimaFechaActualizacionModified
	 */
	public void setUltimaFechaActualizacionModified(boolean ultimaFechaActualizacionModified)
	{
		this.ultimaFechaActualizacionModified = ultimaFechaActualizacionModified;
	}

	/** 
	 * Gets the value of ultimaFechaActualizacionModified
	 */
	public boolean isUltimaFechaActualizacionModified()
	{
		return ultimaFechaActualizacionModified;
	}

	/**
	 * Method 'getUltimoUsuarioActualizacion'
	 * 
	 * @return String
	 */
	public String getUltimoUsuarioActualizacion()
	{
		return ultimoUsuarioActualizacion;
	}

	/**
	 * Method 'setUltimoUsuarioActualizacion'
	 * 
	 * @param ultimoUsuarioActualizacion
	 */
	public void setUltimoUsuarioActualizacion(String ultimoUsuarioActualizacion)
	{
		this.ultimoUsuarioActualizacion = ultimoUsuarioActualizacion;
		this.ultimoUsuarioActualizacionModified = true;
	}

	/** 
	 * Sets the value of ultimoUsuarioActualizacionModified
	 */
	public void setUltimoUsuarioActualizacionModified(boolean ultimoUsuarioActualizacionModified)
	{
		this.ultimoUsuarioActualizacionModified = ultimoUsuarioActualizacionModified;
	}

	/** 
	 * Gets the value of ultimoUsuarioActualizacionModified
	 */
	public boolean isUltimoUsuarioActualizacionModified()
	{
		return ultimoUsuarioActualizacionModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Pedidos)) {
			return false;
		}
		
		final Pedidos _cast = (Pedidos) _other;
		if (idPedido == null ? _cast.idPedido != idPedido : !idPedido.equals( _cast.idPedido )) {
			return false;
		}
		
		if (idPedidoModified != _cast.idPedidoModified) {
			return false;
		}
		
		if (idUsuario == null ? _cast.idUsuario != idUsuario : !idUsuario.equals( _cast.idUsuario )) {
			return false;
		}
		
		if (idUsuarioModified != _cast.idUsuarioModified) {
			return false;
		}
		
		if (folio != _cast.folio) {
			return false;
		}
		
		if (folioNull != _cast.folioNull) {
			return false;
		}
		
		if (folioModified != _cast.folioModified) {
			return false;
		}
		
		if (claveCliente == null ? _cast.claveCliente != claveCliente : !claveCliente.equals( _cast.claveCliente )) {
			return false;
		}
		
		if (claveClienteModified != _cast.claveClienteModified) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (fechaModified != _cast.fechaModified) {
			return false;
		}
		
		if (estatus != _cast.estatus) {
			return false;
		}
		
		if (estatusNull != _cast.estatusNull) {
			return false;
		}
		
		if (estatusModified != _cast.estatusModified) {
			return false;
		}
		
		if (subtotal != _cast.subtotal) {
			return false;
		}
		
		if (subtotalNull != _cast.subtotalNull) {
			return false;
		}
		
		if (subtotalModified != _cast.subtotalModified) {
			return false;
		}
		
		if (iva != _cast.iva) {
			return false;
		}
		
		if (ivaNull != _cast.ivaNull) {
			return false;
		}
		
		if (ivaModified != _cast.ivaModified) {
			return false;
		}
		
		if (total != _cast.total) {
			return false;
		}
		
		if (totalNull != _cast.totalNull) {
			return false;
		}
		
		if (totalModified != _cast.totalModified) {
			return false;
		}
		
		if (observaciones == null ? _cast.observaciones != observaciones : !observaciones.equals( _cast.observaciones )) {
			return false;
		}
		
		if (observacionesModified != _cast.observacionesModified) {
			return false;
		}
		
		if (ultimaFechaActualizacion == null ? _cast.ultimaFechaActualizacion != ultimaFechaActualizacion : !ultimaFechaActualizacion.equals( _cast.ultimaFechaActualizacion )) {
			return false;
		}
		
		if (ultimaFechaActualizacionModified != _cast.ultimaFechaActualizacionModified) {
			return false;
		}
		
		if (ultimoUsuarioActualizacion == null ? _cast.ultimoUsuarioActualizacion != ultimoUsuarioActualizacion : !ultimoUsuarioActualizacion.equals( _cast.ultimoUsuarioActualizacion )) {
			return false;
		}
		
		if (ultimoUsuarioActualizacionModified != _cast.ultimoUsuarioActualizacionModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idPedido != null) {
			_hashCode = 29 * _hashCode + idPedido.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idPedidoModified ? 1 : 0);
		if (idUsuario != null) {
			_hashCode = 29 * _hashCode + idUsuario.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idUsuarioModified ? 1 : 0);
		_hashCode = 29 * _hashCode + folio;
		_hashCode = 29 * _hashCode + (folioNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (folioModified ? 1 : 0);
		if (claveCliente != null) {
			_hashCode = 29 * _hashCode + claveCliente.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (claveClienteModified ? 1 : 0);
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) estatus;
		_hashCode = 29 * _hashCode + (estatusNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (estatusModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(subtotal);
		_hashCode = 29 * _hashCode + (subtotalNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (subtotalModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(iva);
		_hashCode = 29 * _hashCode + (ivaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (ivaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(total);
		_hashCode = 29 * _hashCode + (totalNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (totalModified ? 1 : 0);
		if (observaciones != null) {
			_hashCode = 29 * _hashCode + observaciones.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (observacionesModified ? 1 : 0);
		if (ultimaFechaActualizacion != null) {
			_hashCode = 29 * _hashCode + ultimaFechaActualizacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (ultimaFechaActualizacionModified ? 1 : 0);
		if (ultimoUsuarioActualizacion != null) {
			_hashCode = 29 * _hashCode + ultimoUsuarioActualizacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (ultimoUsuarioActualizacionModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.innovati.felipehernandez.invenenvios.clases.dto.Pedidos: " );
		ret.append( "idPedido=" + idPedido );
		ret.append( ", idUsuario=" + idUsuario );
		ret.append( ", folio=" + folio );
		ret.append( ", claveCliente=" + claveCliente );
		ret.append( ", fecha=" + fecha );
		ret.append( ", estatus=" + estatus );
		ret.append( ", subtotal=" + subtotal );
		ret.append( ", iva=" + iva );
		ret.append( ", total=" + total );
		ret.append( ", observaciones=" + observaciones );
		ret.append( ", ultimaFechaActualizacion=" + ultimaFechaActualizacion );
		ret.append( ", ultimoUsuarioActualizacion=" + ultimoUsuarioActualizacion );
		return ret.toString();
	}

}
