/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.dto;

import com.innovati.felipehernandez.invenenvios.clases.dao.*;
import com.innovati.felipehernandez.invenenvios.clases.factory.*;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Pedidos implements Serializable
{
	/** 
	 * This attribute maps to the column IdPedido in the Pedidos table.
	 */
	protected String idPedido;

	/** 
	 * This attribute maps to the column IdUsuario in the Pedidos table.
	 */
	protected String idUsuario;

	/** 
	 * This attribute maps to the column ClaveCliente in the Pedidos table.
	 */
	protected String claveCliente;

	/** 
	 * This attribute maps to the column Fecha in the Pedidos table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column Estatus in the Pedidos table.
	 */
	protected short estatus;

	/** 
	 * This attribute represents whether the primitive attribute estatus is null.
	 */
	protected boolean estatusNull = true;

	/** 
	 * This attribute maps to the column Subtotal in the Pedidos table.
	 */
	protected float subtotal;

	/** 
	 * This attribute represents whether the primitive attribute subtotal is null.
	 */
	protected boolean subtotalNull = true;

	/** 
	 * This attribute maps to the column IVA in the Pedidos table.
	 */
	protected float iva;

	/** 
	 * This attribute represents whether the primitive attribute iva is null.
	 */
	protected boolean ivaNull = true;

	/** 
	 * This attribute maps to the column Total in the Pedidos table.
	 */
	protected float total;

	/** 
	 * This attribute represents whether the primitive attribute total is null.
	 */
	protected boolean totalNull = true;

	/** 
	 * This attribute maps to the column Observaciones in the Pedidos table.
	 */
	protected String observaciones;

	/** 
	 * This attribute maps to the column UltimaFechaActualizacion in the Pedidos table.
	 */
	protected Date ultimaFechaActualizacion;

	/** 
	 * This attribute maps to the column UltimoUsuarioActualizacion in the Pedidos table.
	 */
	protected String ultimoUsuarioActualizacion;

	/**
	 * Method 'Pedidos'
	 * 
	 */
	public Pedidos()
	{
	}

	/**
	 * Method 'getIdPedido'
	 * 
	 * @return String
	 */
	public String getIdPedido()
	{
		return idPedido;
	}

	/**
	 * Method 'setIdPedido'
	 * 
	 * @param idPedido
	 */
	public void setIdPedido(String idPedido)
	{
		this.idPedido = idPedido;
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return String
	 */
	public String getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(String idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	/**
	 * Method 'getClaveCliente'
	 * 
	 * @return String
	 */
	public String getClaveCliente()
	{
		return claveCliente;
	}

	/**
	 * Method 'setClaveCliente'
	 * 
	 * @param claveCliente
	 */
	public void setClaveCliente(String claveCliente)
	{
		this.claveCliente = claveCliente;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getEstatus'
	 * 
	 * @return short
	 */
	public short getEstatus()
	{
		return estatus;
	}

	/**
	 * Method 'setEstatus'
	 * 
	 * @param estatus
	 */
	public void setEstatus(short estatus)
	{
		this.estatus = estatus;
		this.estatusNull = false;
	}

	/**
	 * Method 'setEstatusNull'
	 * 
	 * @param value
	 */
	public void setEstatusNull(boolean value)
	{
		this.estatusNull = value;
	}

	/**
	 * Method 'isEstatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isEstatusNull()
	{
		return estatusNull;
	}

	/**
	 * Method 'getSubtotal'
	 * 
	 * @return float
	 */
	public float getSubtotal()
	{
		return subtotal;
	}

	/**
	 * Method 'setSubtotal'
	 * 
	 * @param subtotal
	 */
	public void setSubtotal(float subtotal)
	{
		this.subtotal = subtotal;
		this.subtotalNull = false;
	}

	/**
	 * Method 'setSubtotalNull'
	 * 
	 * @param value
	 */
	public void setSubtotalNull(boolean value)
	{
		this.subtotalNull = value;
	}

	/**
	 * Method 'isSubtotalNull'
	 * 
	 * @return boolean
	 */
	public boolean isSubtotalNull()
	{
		return subtotalNull;
	}

	/**
	 * Method 'getIva'
	 * 
	 * @return float
	 */
	public float getIva()
	{
		return iva;
	}

	/**
	 * Method 'setIva'
	 * 
	 * @param iva
	 */
	public void setIva(float iva)
	{
		this.iva = iva;
		this.ivaNull = false;
	}

	/**
	 * Method 'setIvaNull'
	 * 
	 * @param value
	 */
	public void setIvaNull(boolean value)
	{
		this.ivaNull = value;
	}

	/**
	 * Method 'isIvaNull'
	 * 
	 * @return boolean
	 */
	public boolean isIvaNull()
	{
		return ivaNull;
	}

	/**
	 * Method 'getTotal'
	 * 
	 * @return float
	 */
	public float getTotal()
	{
		return total;
	}

	/**
	 * Method 'setTotal'
	 * 
	 * @param total
	 */
	public void setTotal(float total)
	{
		this.total = total;
		this.totalNull = false;
	}

	/**
	 * Method 'setTotalNull'
	 * 
	 * @param value
	 */
	public void setTotalNull(boolean value)
	{
		this.totalNull = value;
	}

	/**
	 * Method 'isTotalNull'
	 * 
	 * @return boolean
	 */
	public boolean isTotalNull()
	{
		return totalNull;
	}

	/**
	 * Method 'getObservaciones'
	 * 
	 * @return String
	 */
	public String getObservaciones()
	{
		return observaciones;
	}

	/**
	 * Method 'setObservaciones'
	 * 
	 * @param observaciones
	 */
	public void setObservaciones(String observaciones)
	{
		this.observaciones = observaciones;
	}

	/**
	 * Method 'getUltimaFechaActualizacion'
	 * 
	 * @return Date
	 */
	public Date getUltimaFechaActualizacion()
	{
		return ultimaFechaActualizacion;
	}

	/**
	 * Method 'setUltimaFechaActualizacion'
	 * 
	 * @param ultimaFechaActualizacion
	 */
	public void setUltimaFechaActualizacion(Date ultimaFechaActualizacion)
	{
		this.ultimaFechaActualizacion = ultimaFechaActualizacion;
	}

	/**
	 * Method 'getUltimoUsuarioActualizacion'
	 * 
	 * @return String
	 */
	public String getUltimoUsuarioActualizacion()
	{
		return ultimoUsuarioActualizacion;
	}

	/**
	 * Method 'setUltimoUsuarioActualizacion'
	 * 
	 * @param ultimoUsuarioActualizacion
	 */
	public void setUltimoUsuarioActualizacion(String ultimoUsuarioActualizacion)
	{
		this.ultimoUsuarioActualizacion = ultimoUsuarioActualizacion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Pedidos)) {
			return false;
		}
		
		final Pedidos _cast = (Pedidos) _other;
		if (idPedido == null ? _cast.idPedido != idPedido : !idPedido.equals( _cast.idPedido )) {
			return false;
		}
		
		if (idUsuario == null ? _cast.idUsuario != idUsuario : !idUsuario.equals( _cast.idUsuario )) {
			return false;
		}
		
		if (claveCliente == null ? _cast.claveCliente != claveCliente : !claveCliente.equals( _cast.claveCliente )) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (estatus != _cast.estatus) {
			return false;
		}
		
		if (estatusNull != _cast.estatusNull) {
			return false;
		}
		
		if (subtotal != _cast.subtotal) {
			return false;
		}
		
		if (subtotalNull != _cast.subtotalNull) {
			return false;
		}
		
		if (iva != _cast.iva) {
			return false;
		}
		
		if (ivaNull != _cast.ivaNull) {
			return false;
		}
		
		if (total != _cast.total) {
			return false;
		}
		
		if (totalNull != _cast.totalNull) {
			return false;
		}
		
		if (observaciones == null ? _cast.observaciones != observaciones : !observaciones.equals( _cast.observaciones )) {
			return false;
		}
		
		if (ultimaFechaActualizacion == null ? _cast.ultimaFechaActualizacion != ultimaFechaActualizacion : !ultimaFechaActualizacion.equals( _cast.ultimaFechaActualizacion )) {
			return false;
		}
		
		if (ultimoUsuarioActualizacion == null ? _cast.ultimoUsuarioActualizacion != ultimoUsuarioActualizacion : !ultimoUsuarioActualizacion.equals( _cast.ultimoUsuarioActualizacion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idPedido != null) {
			_hashCode = 29 * _hashCode + idPedido.hashCode();
		}
		
		if (idUsuario != null) {
			_hashCode = 29 * _hashCode + idUsuario.hashCode();
		}
		
		if (claveCliente != null) {
			_hashCode = 29 * _hashCode + claveCliente.hashCode();
		}
		
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) estatus;
		_hashCode = 29 * _hashCode + (estatusNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(subtotal);
		_hashCode = 29 * _hashCode + (subtotalNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(iva);
		_hashCode = 29 * _hashCode + (ivaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(total);
		_hashCode = 29 * _hashCode + (totalNull ? 1 : 0);
		if (observaciones != null) {
			_hashCode = 29 * _hashCode + observaciones.hashCode();
		}
		
		if (ultimaFechaActualizacion != null) {
			_hashCode = 29 * _hashCode + ultimaFechaActualizacion.hashCode();
		}
		
		if (ultimoUsuarioActualizacion != null) {
			_hashCode = 29 * _hashCode + ultimoUsuarioActualizacion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.innovati.felipehernandez.invenenvios.clases.dto.Pedidos: " );
		ret.append( "idPedido=" + idPedido );
		ret.append( ", idUsuario=" + idUsuario );
		ret.append( ", claveCliente=" + claveCliente );
		ret.append( ", fecha=" + fecha );
		ret.append( ", estatus=" + estatus );
		ret.append( ", subtotal=" + subtotal );
		ret.append( ", iva=" + iva );
		ret.append( ", total=" + total );
		ret.append( ", observaciones=" + observaciones );
		ret.append( ", ultimaFechaActualizacion=" + ultimaFechaActualizacion );
		ret.append( ", ultimoUsuarioActualizacion=" + ultimoUsuarioActualizacion );
		return ret.toString();
	}

}
