/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.dto;

import com.innovati.felipehernandez.invenenvios.clases.dao.*;
import com.innovati.felipehernandez.invenenvios.clases.factory.*;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class VwAbastecimiento implements Serializable
{
	/** 
	 * This attribute maps to the column Nombre in the vwAbastecimiento table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column Total in the vwAbastecimiento table.
	 */
	protected double total;

	/** 
	 * This attribute represents whether the primitive attribute total is null.
	 */
	protected boolean totalNull = true;

	/** 
	 * This attribute maps to the column UnidadPrimaria in the vwAbastecimiento table.
	 */
	protected String unidadPrimaria;

	/**
	 * Method 'VwAbastecimiento'
	 * 
	 */
	public VwAbastecimiento()
	{
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getTotal'
	 * 
	 * @return double
	 */
	public double getTotal()
	{
		return total;
	}

	/**
	 * Method 'setTotal'
	 * 
	 * @param total
	 */
	public void setTotal(double total)
	{
		this.total = total;
		this.totalNull = false;
	}

	/**
	 * Method 'setTotalNull'
	 * 
	 * @param value
	 */
	public void setTotalNull(boolean value)
	{
		this.totalNull = value;
	}

	/**
	 * Method 'isTotalNull'
	 * 
	 * @return boolean
	 */
	public boolean isTotalNull()
	{
		return totalNull;
	}

	/**
	 * Method 'getUnidadPrimaria'
	 * 
	 * @return String
	 */
	public String getUnidadPrimaria()
	{
		return unidadPrimaria;
	}

	/**
	 * Method 'setUnidadPrimaria'
	 * 
	 * @param unidadPrimaria
	 */
	public void setUnidadPrimaria(String unidadPrimaria)
	{
		this.unidadPrimaria = unidadPrimaria;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof VwAbastecimiento)) {
			return false;
		}
		
		final VwAbastecimiento _cast = (VwAbastecimiento) _other;
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (total != _cast.total) {
			return false;
		}
		
		if (totalNull != _cast.totalNull) {
			return false;
		}
		
		if (unidadPrimaria == null ? _cast.unidadPrimaria != unidadPrimaria : !unidadPrimaria.equals( _cast.unidadPrimaria )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		long temp_total = Double.doubleToLongBits(total);
		_hashCode = 29 * _hashCode + (int) (temp_total ^ (temp_total >>> 32));
		_hashCode = 29 * _hashCode + (totalNull ? 1 : 0);
		if (unidadPrimaria != null) {
			_hashCode = 29 * _hashCode + unidadPrimaria.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.innovati.felipehernandez.invenenvios.clases.dto.VwAbastecimiento: " );
		ret.append( "nombre=" + nombre );
		ret.append( ", total=" + total );
		ret.append( ", unidadPrimaria=" + unidadPrimaria );
		return ret.toString();
	}

}
