/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.dto;

import com.innovati.felipehernandez.invenenvios.clases.dao.*;
import com.innovati.felipehernandez.invenenvios.clases.factory.*;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class VwDetallePedido implements Serializable
{
	/** 
	 * This attribute maps to the column IdDetallePedido in the vwDetallePedido table.
	 */
	protected String idDetallePedido;

	/** 
	 * This attribute maps to the column ClaveArticulo in the vwDetallePedido table.
	 */
	protected String claveArticulo;

	/** 
	 * This attribute maps to the column Nombre in the vwDetallePedido table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column UnidadPrimaria in the vwDetallePedido table.
	 */
	protected String unidadPrimaria;

	/** 
	 * This attribute maps to the column Cantidad in the vwDetallePedido table.
	 */
	protected double cantidad;

	/** 
	 * This attribute represents whether the primitive attribute cantidad is null.
	 */
	protected boolean cantidadNull = true;

	/** 
	 * This attribute maps to the column Precio in the vwDetallePedido table.
	 */
	protected float precio;

	/** 
	 * This attribute represents whether the primitive attribute precio is null.
	 */
	protected boolean precioNull = true;

	/** 
	 * This attribute maps to the column Subtotal in the vwDetallePedido table.
	 */
	protected float subtotal;

	/** 
	 * This attribute represents whether the primitive attribute subtotal is null.
	 */
	protected boolean subtotalNull = true;

	/** 
	 * This attribute maps to the column IVA in the vwDetallePedido table.
	 */
	protected float iva;

	/** 
	 * This attribute represents whether the primitive attribute iva is null.
	 */
	protected boolean ivaNull = true;

	/** 
	 * This attribute maps to the column Total in the vwDetallePedido table.
	 */
	protected float total;

	/** 
	 * This attribute represents whether the primitive attribute total is null.
	 */
	protected boolean totalNull = true;

	/** 
	 * This attribute maps to the column UltimaFechaActualizacion in the vwDetallePedido table.
	 */
	protected Date ultimaFechaActualizacion;

	/** 
	 * This attribute maps to the column UltimoUsuarioActualizacion in the vwDetallePedido table.
	 */
	protected String ultimoUsuarioActualizacion;

	/** 
	 * This attribute maps to the column IdPedido in the vwDetallePedido table.
	 */
	protected String idPedido;

	/** 
	 * This attribute maps to the column Surtido in the vwDetallePedido table.
	 */
	protected short surtido;

	/** 
	 * This attribute represents whether the primitive attribute surtido is null.
	 */
	protected boolean surtidoNull = true;

	/**
	 * Method 'VwDetallePedido'
	 * 
	 */
	public VwDetallePedido()
	{
	}

	/**
	 * Method 'getIdDetallePedido'
	 * 
	 * @return String
	 */
	public String getIdDetallePedido()
	{
		return idDetallePedido;
	}

	/**
	 * Method 'setIdDetallePedido'
	 * 
	 * @param idDetallePedido
	 */
	public void setIdDetallePedido(String idDetallePedido)
	{
		this.idDetallePedido = idDetallePedido;
	}

	/**
	 * Method 'getClaveArticulo'
	 * 
	 * @return String
	 */
	public String getClaveArticulo()
	{
		return claveArticulo;
	}

	/**
	 * Method 'setClaveArticulo'
	 * 
	 * @param claveArticulo
	 */
	public void setClaveArticulo(String claveArticulo)
	{
		this.claveArticulo = claveArticulo;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getUnidadPrimaria'
	 * 
	 * @return String
	 */
	public String getUnidadPrimaria()
	{
		return unidadPrimaria;
	}

	/**
	 * Method 'setUnidadPrimaria'
	 * 
	 * @param unidadPrimaria
	 */
	public void setUnidadPrimaria(String unidadPrimaria)
	{
		this.unidadPrimaria = unidadPrimaria;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return double
	 */
	public double getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(double cantidad)
	{
		this.cantidad = cantidad;
		this.cantidadNull = false;
	}

	/**
	 * Method 'setCantidadNull'
	 * 
	 * @param value
	 */
	public void setCantidadNull(boolean value)
	{
		this.cantidadNull = value;
	}

	/**
	 * Method 'isCantidadNull'
	 * 
	 * @return boolean
	 */
	public boolean isCantidadNull()
	{
		return cantidadNull;
	}

	/**
	 * Method 'getPrecio'
	 * 
	 * @return float
	 */
	public float getPrecio()
	{
		return precio;
	}

	/**
	 * Method 'setPrecio'
	 * 
	 * @param precio
	 */
	public void setPrecio(float precio)
	{
		this.precio = precio;
		this.precioNull = false;
	}

	/**
	 * Method 'setPrecioNull'
	 * 
	 * @param value
	 */
	public void setPrecioNull(boolean value)
	{
		this.precioNull = value;
	}

	/**
	 * Method 'isPrecioNull'
	 * 
	 * @return boolean
	 */
	public boolean isPrecioNull()
	{
		return precioNull;
	}

	/**
	 * Method 'getSubtotal'
	 * 
	 * @return float
	 */
	public float getSubtotal()
	{
		return subtotal;
	}

	/**
	 * Method 'setSubtotal'
	 * 
	 * @param subtotal
	 */
	public void setSubtotal(float subtotal)
	{
		this.subtotal = subtotal;
		this.subtotalNull = false;
	}

	/**
	 * Method 'setSubtotalNull'
	 * 
	 * @param value
	 */
	public void setSubtotalNull(boolean value)
	{
		this.subtotalNull = value;
	}

	/**
	 * Method 'isSubtotalNull'
	 * 
	 * @return boolean
	 */
	public boolean isSubtotalNull()
	{
		return subtotalNull;
	}

	/**
	 * Method 'getIva'
	 * 
	 * @return float
	 */
	public float getIva()
	{
		return iva;
	}

	/**
	 * Method 'setIva'
	 * 
	 * @param iva
	 */
	public void setIva(float iva)
	{
		this.iva = iva;
		this.ivaNull = false;
	}

	/**
	 * Method 'setIvaNull'
	 * 
	 * @param value
	 */
	public void setIvaNull(boolean value)
	{
		this.ivaNull = value;
	}

	/**
	 * Method 'isIvaNull'
	 * 
	 * @return boolean
	 */
	public boolean isIvaNull()
	{
		return ivaNull;
	}

	/**
	 * Method 'getTotal'
	 * 
	 * @return float
	 */
	public float getTotal()
	{
		return total;
	}

	/**
	 * Method 'setTotal'
	 * 
	 * @param total
	 */
	public void setTotal(float total)
	{
		this.total = total;
		this.totalNull = false;
	}

	/**
	 * Method 'setTotalNull'
	 * 
	 * @param value
	 */
	public void setTotalNull(boolean value)
	{
		this.totalNull = value;
	}

	/**
	 * Method 'isTotalNull'
	 * 
	 * @return boolean
	 */
	public boolean isTotalNull()
	{
		return totalNull;
	}

	/**
	 * Method 'getUltimaFechaActualizacion'
	 * 
	 * @return Date
	 */
	public Date getUltimaFechaActualizacion()
	{
		return ultimaFechaActualizacion;
	}

	/**
	 * Method 'setUltimaFechaActualizacion'
	 * 
	 * @param ultimaFechaActualizacion
	 */
	public void setUltimaFechaActualizacion(Date ultimaFechaActualizacion)
	{
		this.ultimaFechaActualizacion = ultimaFechaActualizacion;
	}

	/**
	 * Method 'getUltimoUsuarioActualizacion'
	 * 
	 * @return String
	 */
	public String getUltimoUsuarioActualizacion()
	{
		return ultimoUsuarioActualizacion;
	}

	/**
	 * Method 'setUltimoUsuarioActualizacion'
	 * 
	 * @param ultimoUsuarioActualizacion
	 */
	public void setUltimoUsuarioActualizacion(String ultimoUsuarioActualizacion)
	{
		this.ultimoUsuarioActualizacion = ultimoUsuarioActualizacion;
	}

	/**
	 * Method 'getIdPedido'
	 * 
	 * @return String
	 */
	public String getIdPedido()
	{
		return idPedido;
	}

	/**
	 * Method 'setIdPedido'
	 * 
	 * @param idPedido
	 */
	public void setIdPedido(String idPedido)
	{
		this.idPedido = idPedido;
	}

	/**
	 * Method 'getSurtido'
	 * 
	 * @return short
	 */
	public short getSurtido()
	{
		return surtido;
	}

	/**
	 * Method 'setSurtido'
	 * 
	 * @param surtido
	 */
	public void setSurtido(short surtido)
	{
		this.surtido = surtido;
		this.surtidoNull = false;
	}

	/**
	 * Method 'setSurtidoNull'
	 * 
	 * @param value
	 */
	public void setSurtidoNull(boolean value)
	{
		this.surtidoNull = value;
	}

	/**
	 * Method 'isSurtidoNull'
	 * 
	 * @return boolean
	 */
	public boolean isSurtidoNull()
	{
		return surtidoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof VwDetallePedido)) {
			return false;
		}
		
		final VwDetallePedido _cast = (VwDetallePedido) _other;
		if (idDetallePedido == null ? _cast.idDetallePedido != idDetallePedido : !idDetallePedido.equals( _cast.idDetallePedido )) {
			return false;
		}
		
		if (claveArticulo == null ? _cast.claveArticulo != claveArticulo : !claveArticulo.equals( _cast.claveArticulo )) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (unidadPrimaria == null ? _cast.unidadPrimaria != unidadPrimaria : !unidadPrimaria.equals( _cast.unidadPrimaria )) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (cantidadNull != _cast.cantidadNull) {
			return false;
		}
		
		if (precio != _cast.precio) {
			return false;
		}
		
		if (precioNull != _cast.precioNull) {
			return false;
		}
		
		if (subtotal != _cast.subtotal) {
			return false;
		}
		
		if (subtotalNull != _cast.subtotalNull) {
			return false;
		}
		
		if (iva != _cast.iva) {
			return false;
		}
		
		if (ivaNull != _cast.ivaNull) {
			return false;
		}
		
		if (total != _cast.total) {
			return false;
		}
		
		if (totalNull != _cast.totalNull) {
			return false;
		}
		
		if (ultimaFechaActualizacion == null ? _cast.ultimaFechaActualizacion != ultimaFechaActualizacion : !ultimaFechaActualizacion.equals( _cast.ultimaFechaActualizacion )) {
			return false;
		}
		
		if (ultimoUsuarioActualizacion == null ? _cast.ultimoUsuarioActualizacion != ultimoUsuarioActualizacion : !ultimoUsuarioActualizacion.equals( _cast.ultimoUsuarioActualizacion )) {
			return false;
		}
		
		if (idPedido == null ? _cast.idPedido != idPedido : !idPedido.equals( _cast.idPedido )) {
			return false;
		}
		
		if (surtido != _cast.surtido) {
			return false;
		}
		
		if (surtidoNull != _cast.surtidoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idDetallePedido != null) {
			_hashCode = 29 * _hashCode + idDetallePedido.hashCode();
		}
		
		if (claveArticulo != null) {
			_hashCode = 29 * _hashCode + claveArticulo.hashCode();
		}
		
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		if (unidadPrimaria != null) {
			_hashCode = 29 * _hashCode + unidadPrimaria.hashCode();
		}
		
		long temp_cantidad = Double.doubleToLongBits(cantidad);
		_hashCode = 29 * _hashCode + (int) (temp_cantidad ^ (temp_cantidad >>> 32));
		_hashCode = 29 * _hashCode + (cantidadNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(precio);
		_hashCode = 29 * _hashCode + (precioNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(subtotal);
		_hashCode = 29 * _hashCode + (subtotalNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(iva);
		_hashCode = 29 * _hashCode + (ivaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(total);
		_hashCode = 29 * _hashCode + (totalNull ? 1 : 0);
		if (ultimaFechaActualizacion != null) {
			_hashCode = 29 * _hashCode + ultimaFechaActualizacion.hashCode();
		}
		
		if (ultimoUsuarioActualizacion != null) {
			_hashCode = 29 * _hashCode + ultimoUsuarioActualizacion.hashCode();
		}
		
		if (idPedido != null) {
			_hashCode = 29 * _hashCode + idPedido.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) surtido;
		_hashCode = 29 * _hashCode + (surtidoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.innovati.felipehernandez.invenenvios.clases.dto.VwDetallePedido: " );
		ret.append( "idDetallePedido=" + idDetallePedido );
		ret.append( ", claveArticulo=" + claveArticulo );
		ret.append( ", nombre=" + nombre );
		ret.append( ", unidadPrimaria=" + unidadPrimaria );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", precio=" + precio );
		ret.append( ", subtotal=" + subtotal );
		ret.append( ", iva=" + iva );
		ret.append( ", total=" + total );
		ret.append( ", ultimaFechaActualizacion=" + ultimaFechaActualizacion );
		ret.append( ", ultimoUsuarioActualizacion=" + ultimoUsuarioActualizacion );
		ret.append( ", idPedido=" + idPedido );
		ret.append( ", surtido=" + surtido );
		return ret.toString();
	}

}
