/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.dto;

import com.innovati.felipehernandez.invenenvios.clases.dao.*;
import com.innovati.felipehernandez.invenenvios.clases.factory.*;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.*;
import java.io.Serializable;
import java.util.Date;

public class VwUsuarios implements Serializable
{
	/** 
	 * This attribute maps to the column IdUsuario in the vwUsuarios table.
	 */
	protected String idUsuario;

	/** 
	 * This attribute maps to the column Clave in the vwUsuarios table.
	 */
	protected String clave;

	/** 
	 * This attribute maps to the column NickName in the vwUsuarios table.
	 */
	protected String nickName;

	/** 
	 * This attribute maps to the column Password in the vwUsuarios table.
	 */
	protected String password;

	/** 
	 * This attribute maps to the column Status in the vwUsuarios table.
	 */
	protected short status;

	/** 
	 * This attribute maps to the column FechaActualizacion in the vwUsuarios table.
	 */
	protected Date fechaActualizacion;

	/** 
	 * This attribute maps to the column IdUsuarioActualizacion in the vwUsuarios table.
	 */
	protected String idUsuarioActualizacion;

	/** 
	 * This attribute maps to the column Sucursal in the vwUsuarios table.
	 */
	protected String sucursal;

	/**
	 * Method 'VwUsuarios'
	 * 
	 */
	public VwUsuarios()
	{
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return String
	 */
	public String getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(String idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	/**
	 * Method 'getClave'
	 * 
	 * @return String
	 */
	public String getClave()
	{
		return clave;
	}

	/**
	 * Method 'setClave'
	 * 
	 * @param clave
	 */
	public void setClave(String clave)
	{
		this.clave = clave;
	}

	/**
	 * Method 'getNickName'
	 * 
	 * @return String
	 */
	public String getNickName()
	{
		return nickName;
	}

	/**
	 * Method 'setNickName'
	 * 
	 * @param nickName
	 */
	public void setNickName(String nickName)
	{
		this.nickName = nickName;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/**
	 * Method 'getStatus'
	 * 
	 * @return short
	 */
	public short getStatus()
	{
		return status;
	}

	/**
	 * Method 'setStatus'
	 * 
	 * @param status
	 */
	public void setStatus(short status)
	{
		this.status = status;
	}

	/**
	 * Method 'getFechaActualizacion'
	 * 
	 * @return Date
	 */
	public Date getFechaActualizacion()
	{
		return fechaActualizacion;
	}

	/**
	 * Method 'setFechaActualizacion'
	 * 
	 * @param fechaActualizacion
	 */
	public void setFechaActualizacion(Date fechaActualizacion)
	{
		this.fechaActualizacion = fechaActualizacion;
	}

	/**
	 * Method 'getIdUsuarioActualizacion'
	 * 
	 * @return String
	 */
	public String getIdUsuarioActualizacion()
	{
		return idUsuarioActualizacion;
	}

	/**
	 * Method 'setIdUsuarioActualizacion'
	 * 
	 * @param idUsuarioActualizacion
	 */
	public void setIdUsuarioActualizacion(String idUsuarioActualizacion)
	{
		this.idUsuarioActualizacion = idUsuarioActualizacion;
	}

	/**
	 * Method 'getSucursal'
	 * 
	 * @return String
	 */
	public String getSucursal()
	{
		return sucursal;
	}

	/**
	 * Method 'setSucursal'
	 * 
	 * @param sucursal
	 */
	public void setSucursal(String sucursal)
	{
		this.sucursal = sucursal;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof VwUsuarios)) {
			return false;
		}
		
		final VwUsuarios _cast = (VwUsuarios) _other;
		if (idUsuario == null ? _cast.idUsuario != idUsuario : !idUsuario.equals( _cast.idUsuario )) {
			return false;
		}
		
		if (clave == null ? _cast.clave != clave : !clave.equals( _cast.clave )) {
			return false;
		}
		
		if (nickName == null ? _cast.nickName != nickName : !nickName.equals( _cast.nickName )) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (status != _cast.status) {
			return false;
		}
		
		if (fechaActualizacion == null ? _cast.fechaActualizacion != fechaActualizacion : !fechaActualizacion.equals( _cast.fechaActualizacion )) {
			return false;
		}
		
		if (idUsuarioActualizacion == null ? _cast.idUsuarioActualizacion != idUsuarioActualizacion : !idUsuarioActualizacion.equals( _cast.idUsuarioActualizacion )) {
			return false;
		}
		
		if (sucursal == null ? _cast.sucursal != sucursal : !sucursal.equals( _cast.sucursal )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idUsuario != null) {
			_hashCode = 29 * _hashCode + idUsuario.hashCode();
		}
		
		if (clave != null) {
			_hashCode = 29 * _hashCode + clave.hashCode();
		}
		
		if (nickName != null) {
			_hashCode = 29 * _hashCode + nickName.hashCode();
		}
		
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) status;
		if (fechaActualizacion != null) {
			_hashCode = 29 * _hashCode + fechaActualizacion.hashCode();
		}
		
		if (idUsuarioActualizacion != null) {
			_hashCode = 29 * _hashCode + idUsuarioActualizacion.hashCode();
		}
		
		if (sucursal != null) {
			_hashCode = 29 * _hashCode + sucursal.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.innovati.felipehernandez.invenenvios.dto.VwUsuarios: " );
		ret.append( "idUsuario=" + idUsuario );
		ret.append( ", clave=" + clave );
		ret.append( ", nickName=" + nickName );
		ret.append( ", password=" + password );
		ret.append( ", status=" + status );
		ret.append( ", fechaActualizacion=" + fechaActualizacion );
		ret.append( ", idUsuarioActualizacion=" + idUsuarioActualizacion );
		ret.append( ", sucursal=" + sucursal );
		return ret.toString();
	}

}
