/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.dao;

import java.util.Date;
import com.innovati.felipehernandez.invenenvios.clases.dto.*;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.*;
import java.sql.CallableStatement;

public interface VwDetallePedidoDao
{
	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria ''.
	 */
	public VwDetallePedido[] findAll() throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'IdDetallePedido = :idDetallePedido'.
	 */
	public VwDetallePedido[] findWhereIdDetallePedidoEquals(String idDetallePedido) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'ClaveArticulo = :claveArticulo'.
	 */
	public VwDetallePedido[] findWhereClaveArticuloEquals(String claveArticulo) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Nombre = :nombre'.
	 */
	public VwDetallePedido[] findWhereNombreEquals(String nombre) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'UnidadPrimaria = :unidadPrimaria'.
	 */
	public VwDetallePedido[] findWhereUnidadPrimariaEquals(String unidadPrimaria) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Cantidad = :cantidad'.
	 */
	public VwDetallePedido[] findWhereCantidadEquals(double cantidad) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Precio = :precio'.
	 */
	public VwDetallePedido[] findWherePrecioEquals(float precio) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Subtotal = :subtotal'.
	 */
	public VwDetallePedido[] findWhereSubtotalEquals(float subtotal) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'IVA = :iva'.
	 */
	public VwDetallePedido[] findWhereIvaEquals(float iva) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Total = :total'.
	 */
	public VwDetallePedido[] findWhereTotalEquals(float total) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'UltimaFechaActualizacion = :ultimaFechaActualizacion'.
	 */
	public VwDetallePedido[] findWhereUltimaFechaActualizacionEquals(Date ultimaFechaActualizacion) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'UltimoUsuarioActualizacion = :ultimoUsuarioActualizacion'.
	 */
	public VwDetallePedido[] findWhereUltimoUsuarioActualizacionEquals(String ultimoUsuarioActualizacion) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'IdPedido = :idPedido'.
	 */
	public VwDetallePedido[] findWhereIdPedidoEquals(String idPedido) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Surtido = :surtido'.
	 */
	public VwDetallePedido[] findWhereSurtidoEquals(short surtido) throws VwDetallePedidoDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the vwDetallePedido table that match the specified arbitrary SQL statement
	 */
	public VwDetallePedido[] findByDynamicSelect(String sql, Object[] sqlParams) throws VwDetallePedidoDaoException;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the specified arbitrary SQL statement
	 */
	public VwDetallePedido[] findByDynamicWhere(String sql, Object[] sqlParams) throws VwDetallePedidoDaoException;

}
