/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.jdbc;

import com.innovati.felipehernandez.invenenvios.clases.dao.*;
import com.innovati.felipehernandez.invenenvios.clases.factory.*;
import com.innovati.felipehernandez.invenenvios.clases.dto.*;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;
import java.sql.CallableStatement;

public class VwAbastecimientoDaoImpl extends AbstractDAO implements VwAbastecimientoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT Nombre, Total, UnidadPrimaria FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * Index of column Nombre
	 */
	protected static final int COLUMN_NOMBRE = 1;

	/** 
	 * Index of column Total
	 */
	protected static final int COLUMN_TOTAL = 2;

	/** 
	 * Index of column UnidadPrimaria
	 */
	protected static final int COLUMN_UNIDAD_PRIMARIA = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Returns all rows from the vwAbastecimiento table that match the criteria ''.
	 */
	public VwAbastecimiento[] findAll() throws VwAbastecimientoDaoException
	{
		return findByDynamicSelect( SQL_SELECT, null );
	}

	/** 
	 * Returns all rows from the vwAbastecimiento table that match the criteria 'Nombre = :nombre'.
	 */
	public VwAbastecimiento[] findWhereNombreEquals(String nombre) throws VwAbastecimientoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Nombre = ? ORDER BY Nombre", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the vwAbastecimiento table that match the criteria 'Total = :total'.
	 */
	public VwAbastecimiento[] findWhereTotalEquals(double total) throws VwAbastecimientoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Total = ? ORDER BY Total", new Object[] {  new Double(total) } );
	}

	/** 
	 * Returns all rows from the vwAbastecimiento table that match the criteria 'UnidadPrimaria = :unidadPrimaria'.
	 */
	public VwAbastecimiento[] findWhereUnidadPrimariaEquals(String unidadPrimaria) throws VwAbastecimientoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE UnidadPrimaria = ? ORDER BY UnidadPrimaria", new Object[] { unidadPrimaria } );
	}

	/**
	 * Method 'VwAbastecimientoDaoImpl'
	 * 
	 */
	public VwAbastecimientoDaoImpl()
	{
	}

	/**
	 * Method 'VwAbastecimientoDaoImpl'
	 * 
	 * @param userConn
	 */
	public VwAbastecimientoDaoImpl(final Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "Inven_E..vwAbastecimiento";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected VwAbastecimiento fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			VwAbastecimiento dto = new VwAbastecimiento();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected VwAbastecimiento[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			VwAbastecimiento dto = new VwAbastecimiento();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		VwAbastecimiento ret[] = new VwAbastecimiento[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(VwAbastecimiento dto, ResultSet rs) throws SQLException
	{
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setTotal( rs.getDouble( COLUMN_TOTAL ) );
		if (rs.wasNull()) {
			dto.setTotalNull( true );
		}
		
		dto.setUnidadPrimaria( rs.getString( COLUMN_UNIDAD_PRIMARIA ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(VwAbastecimiento dto)
	{
	}

	/** 
	 * Returns all rows from the vwAbastecimiento table that match the specified arbitrary SQL statement
	 */
	public VwAbastecimiento[] findByDynamicSelect(String sql, Object[] sqlParams) throws VwAbastecimientoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new VwAbastecimientoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the vwAbastecimiento table that match the specified arbitrary SQL statement
	 */
	public VwAbastecimiento[] findByDynamicWhere(String sql, Object[] sqlParams) throws VwAbastecimientoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new VwAbastecimientoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
