/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.jdbc;

import com.innovati.felipehernandez.invenenvios.clases.dao.*;
import com.innovati.felipehernandez.invenenvios.clases.factory.*;
import java.util.Date;
import com.innovati.felipehernandez.invenenvios.clases.dto.*;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;
import java.sql.CallableStatement;

public class VwDetallePedidoDaoImpl extends AbstractDAO implements VwDetallePedidoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT IdPedido, IdDetallePedido, ClaveArticulo, Nombre, UnidadPrimaria, Cantidad, Precio, Subtotal, IVA, Total, UltimaFechaActualizacion, UltimoUsuarioActualizacion FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * Index of column IdPedido
	 */
	protected static final int COLUMN_ID_PEDIDO = 1;

	/** 
	 * Index of column IdDetallePedido
	 */
	protected static final int COLUMN_ID_DETALLE_PEDIDO = 2;

	/** 
	 * Index of column ClaveArticulo
	 */
	protected static final int COLUMN_CLAVE_ARTICULO = 3;

	/** 
	 * Index of column Nombre
	 */
	protected static final int COLUMN_NOMBRE = 4;

	/** 
	 * Index of column UnidadPrimaria
	 */
	protected static final int COLUMN_UNIDAD_PRIMARIA = 5;

	/** 
	 * Index of column Cantidad
	 */
	protected static final int COLUMN_CANTIDAD = 6;

	/** 
	 * Index of column Precio
	 */
	protected static final int COLUMN_PRECIO = 7;

	/** 
	 * Index of column Subtotal
	 */
	protected static final int COLUMN_SUBTOTAL = 8;

	/** 
	 * Index of column IVA
	 */
	protected static final int COLUMN_IVA = 9;

	/** 
	 * Index of column Total
	 */
	protected static final int COLUMN_TOTAL = 10;

	/** 
	 * Index of column UltimaFechaActualizacion
	 */
	protected static final int COLUMN_ULTIMA_FECHA_ACTUALIZACION = 11;

	/** 
	 * Index of column UltimoUsuarioActualizacion
	 */
	protected static final int COLUMN_ULTIMO_USUARIO_ACTUALIZACION = 12;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 12;

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria ''.
	 */
	public VwDetallePedido[] findAll() throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT, null );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'IdPedido = :idPedido'.
	 */
	public VwDetallePedido[] findWhereIdPedidoEquals(String idPedido) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IdPedido = ? ORDER BY IdPedido", new Object[] { idPedido } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'IdDetallePedido = :idDetallePedido'.
	 */
	public VwDetallePedido[] findWhereIdDetallePedidoEquals(String idDetallePedido) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IdDetallePedido = ? ORDER BY IdDetallePedido", new Object[] { idDetallePedido } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'ClaveArticulo = :claveArticulo'.
	 */
	public VwDetallePedido[] findWhereClaveArticuloEquals(String claveArticulo) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ClaveArticulo = ? ORDER BY ClaveArticulo", new Object[] { claveArticulo } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Nombre = :nombre'.
	 */
	public VwDetallePedido[] findWhereNombreEquals(String nombre) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Nombre = ? ORDER BY Nombre", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'UnidadPrimaria = :unidadPrimaria'.
	 */
	public VwDetallePedido[] findWhereUnidadPrimariaEquals(String unidadPrimaria) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE UnidadPrimaria = ? ORDER BY UnidadPrimaria", new Object[] { unidadPrimaria } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Cantidad = :cantidad'.
	 */
	public VwDetallePedido[] findWhereCantidadEquals(double cantidad) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Cantidad = ? ORDER BY Cantidad", new Object[] {  new Double(cantidad) } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Precio = :precio'.
	 */
	public VwDetallePedido[] findWherePrecioEquals(float precio) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Precio = ? ORDER BY Precio", new Object[] {  new Float(precio) } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Subtotal = :subtotal'.
	 */
	public VwDetallePedido[] findWhereSubtotalEquals(float subtotal) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Subtotal = ? ORDER BY Subtotal", new Object[] {  new Float(subtotal) } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'IVA = :iva'.
	 */
	public VwDetallePedido[] findWhereIvaEquals(float iva) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE IVA = ? ORDER BY IVA", new Object[] {  new Float(iva) } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'Total = :total'.
	 */
	public VwDetallePedido[] findWhereTotalEquals(float total) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Total = ? ORDER BY Total", new Object[] {  new Float(total) } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'UltimaFechaActualizacion = :ultimaFechaActualizacion'.
	 */
	public VwDetallePedido[] findWhereUltimaFechaActualizacionEquals(Date ultimaFechaActualizacion) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE UltimaFechaActualizacion = ? ORDER BY UltimaFechaActualizacion", new Object[] { ultimaFechaActualizacion==null ? null : new java.sql.Timestamp( ultimaFechaActualizacion.getTime() ) } );
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the criteria 'UltimoUsuarioActualizacion = :ultimoUsuarioActualizacion'.
	 */
	public VwDetallePedido[] findWhereUltimoUsuarioActualizacionEquals(String ultimoUsuarioActualizacion) throws VwDetallePedidoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE UltimoUsuarioActualizacion = ? ORDER BY UltimoUsuarioActualizacion", new Object[] { ultimoUsuarioActualizacion } );
	}

	/**
	 * Method 'VwDetallePedidoDaoImpl'
	 * 
	 */
	public VwDetallePedidoDaoImpl()
	{
	}

	/**
	 * Method 'VwDetallePedidoDaoImpl'
	 * 
	 * @param userConn
	 */
	public VwDetallePedidoDaoImpl(final Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "Inven_E..vwDetallePedido";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected VwDetallePedido fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			VwDetallePedido dto = new VwDetallePedido();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected VwDetallePedido[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			VwDetallePedido dto = new VwDetallePedido();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		VwDetallePedido ret[] = new VwDetallePedido[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(VwDetallePedido dto, ResultSet rs) throws SQLException
	{
		dto.setIdPedido( rs.getString( COLUMN_ID_PEDIDO ) );
		dto.setIdDetallePedido( rs.getString( COLUMN_ID_DETALLE_PEDIDO ) );
		dto.setClaveArticulo( rs.getString( COLUMN_CLAVE_ARTICULO ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setUnidadPrimaria( rs.getString( COLUMN_UNIDAD_PRIMARIA ) );
		dto.setCantidad( rs.getDouble( COLUMN_CANTIDAD ) );
		if (rs.wasNull()) {
			dto.setCantidadNull( true );
		}
		
		dto.setPrecio( rs.getFloat( COLUMN_PRECIO ) );
		if (rs.wasNull()) {
			dto.setPrecioNull( true );
		}
		
		dto.setSubtotal( rs.getFloat( COLUMN_SUBTOTAL ) );
		if (rs.wasNull()) {
			dto.setSubtotalNull( true );
		}
		
		dto.setIva( rs.getFloat( COLUMN_IVA ) );
		if (rs.wasNull()) {
			dto.setIvaNull( true );
		}
		
		dto.setTotal( rs.getFloat( COLUMN_TOTAL ) );
		if (rs.wasNull()) {
			dto.setTotalNull( true );
		}
		
		dto.setUltimaFechaActualizacion( rs.getTimestamp(COLUMN_ULTIMA_FECHA_ACTUALIZACION ) );
		dto.setUltimoUsuarioActualizacion( rs.getString( COLUMN_ULTIMO_USUARIO_ACTUALIZACION ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(VwDetallePedido dto)
	{
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the specified arbitrary SQL statement
	 */
	public VwDetallePedido[] findByDynamicSelect(String sql, Object[] sqlParams) throws VwDetallePedidoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new VwDetallePedidoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the vwDetallePedido table that match the specified arbitrary SQL statement
	 */
	public VwDetallePedido[] findByDynamicWhere(String sql, Object[] sqlParams) throws VwDetallePedidoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new VwDetallePedidoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
