/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.factory;

import java.sql.Connection;
import com.innovati.felipehernandez.invenenvios.dao.*;
import com.innovati.felipehernandez.invenenvios.jdbc.*;

public class VwUsuariosDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return VwUsuariosDao
	 */
	public static VwUsuariosDao create()
	{
		return new VwUsuariosDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return VwUsuariosDao
	 */
	public static VwUsuariosDao create(Connection conn)
	{
		return new VwUsuariosDaoImpl( conn );
	}

}
