/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.innovati.felipehernandez.invenenvios.clases.dao.PedidosDao;
import com.innovati.felipehernandez.invenenvios.clases.dto.Pedidos;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.PedidosDaoException;
import com.innovati.felipehernandez.invenenvios.clases.factory.PedidosDaoFactory;

public class PedidosDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdPedidoEquals("");
		// findWhereIdUsuarioEquals("");
		// findWhereClaveClienteEquals("");
		// findWhereFechaEquals(null);
		// findWhereEstatusEquals(0);
		// findWhereSubtotalEquals(0);
		// findWhereIvaEquals(0);
		// findWhereTotalEquals(0);
		// findWhereObservacionesEquals("");
		// findWhereUltimaFechaActualizacionEquals(null);
		// findWhereUltimoUsuarioActualizacionEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdPedidoEquals'
	 * 
	 * @param idPedido
	 */
	public static void findWhereIdPedidoEquals(String idPedido)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereIdPedidoEquals(idPedido);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdUsuarioEquals'
	 * 
	 * @param idUsuario
	 */
	public static void findWhereIdUsuarioEquals(String idUsuario)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereIdUsuarioEquals(idUsuario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereClaveClienteEquals'
	 * 
	 * @param claveCliente
	 */
	public static void findWhereClaveClienteEquals(String claveCliente)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereClaveClienteEquals(claveCliente);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaEquals'
	 * 
	 * @param fecha
	 */
	public static void findWhereFechaEquals(Date fecha)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereFechaEquals(fecha);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEstatusEquals'
	 * 
	 * @param estatus
	 */
	public static void findWhereEstatusEquals(short estatus)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereEstatusEquals(estatus);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSubtotalEquals'
	 * 
	 * @param subtotal
	 */
	public static void findWhereSubtotalEquals(float subtotal)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereSubtotalEquals(subtotal);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIvaEquals'
	 * 
	 * @param iva
	 */
	public static void findWhereIvaEquals(float iva)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereIvaEquals(iva);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTotalEquals'
	 * 
	 * @param total
	 */
	public static void findWhereTotalEquals(float total)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereTotalEquals(total);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereObservacionesEquals'
	 * 
	 * @param observaciones
	 */
	public static void findWhereObservacionesEquals(String observaciones)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereObservacionesEquals(observaciones);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUltimaFechaActualizacionEquals'
	 * 
	 * @param ultimaFechaActualizacion
	 */
	public static void findWhereUltimaFechaActualizacionEquals(Date ultimaFechaActualizacion)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereUltimaFechaActualizacionEquals(ultimaFechaActualizacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUltimoUsuarioActualizacionEquals'
	 * 
	 * @param ultimoUsuarioActualizacion
	 */
	public static void findWhereUltimoUsuarioActualizacionEquals(String ultimoUsuarioActualizacion)
	{
		try {
			PedidosDao _dao = getPedidosDao();
			Pedidos _result[] = _dao.findWhereUltimoUsuarioActualizacionEquals(ultimoUsuarioActualizacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getPedidosDao'
	 * 
	 * @return PedidosDao
	 */
	public static PedidosDao getPedidosDao()
	{
		return PedidosDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Pedidos dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdPedido() );
		buf.append( ", " );
		buf.append( dto.getIdUsuario() );
		buf.append( ", " );
		buf.append( dto.getClaveCliente() );
		buf.append( ", " );
		buf.append( dto.getFecha() );
		buf.append( ", " );
		buf.append( dto.getEstatus() );
		buf.append( ", " );
		buf.append( dto.getSubtotal() );
		buf.append( ", " );
		buf.append( dto.getIva() );
		buf.append( ", " );
		buf.append( dto.getTotal() );
		buf.append( ", " );
		buf.append( dto.getObservaciones() );
		buf.append( ", " );
		buf.append( dto.getUltimaFechaActualizacion() );
		buf.append( ", " );
		buf.append( dto.getUltimoUsuarioActualizacion() );
		System.out.println( buf.toString() );
	}

}
