/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.innovati.felipehernandez.invenenvios.clases.dao.VwAgenteDao;
import com.innovati.felipehernandez.invenenvios.clases.dto.VwAgente;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.VwAgenteDaoException;
import com.innovati.felipehernandez.invenenvios.clases.factory.VwAgenteDaoFactory;

public class VwAgenteDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereClaveEquals("");
		// findWhereNombreEquals("");
		// findWhereTelefonoEquals("");
		// findWhereCelularEquals("");
		// findWhereComisionEquals(0);
		// findWhereEmailEquals("");
		// findWhereSucursalEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			VwAgenteDao _dao = getVwAgenteDao();
			VwAgente _result[] = _dao.findAll();

			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereClaveEquals'
	 * 
	 * @param clave
	 */
	public static void findWhereClaveEquals(String clave)
	{
		try {
			VwAgenteDao _dao = getVwAgenteDao();
			VwAgente _result[] = _dao.findWhereClaveEquals(clave);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreEquals'
	 * 
	 * @param nombre
	 */
	public static void findWhereNombreEquals(String nombre)
	{
		try {
			VwAgenteDao _dao = getVwAgenteDao();
			VwAgente _result[] = _dao.findWhereNombreEquals(nombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTelefonoEquals'
	 * 
	 * @param telefono
	 */
	public static void findWhereTelefonoEquals(String telefono)
	{
		try {
			VwAgenteDao _dao = getVwAgenteDao();
			VwAgente _result[] = _dao.findWhereTelefonoEquals(telefono);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCelularEquals'
	 * 
	 * @param celular
	 */
	public static void findWhereCelularEquals(String celular)
	{
		try {
			VwAgenteDao _dao = getVwAgenteDao();
			VwAgente _result[] = _dao.findWhereCelularEquals(celular);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereComisionEquals'
	 * 
	 * @param comision
	 */
	public static void findWhereComisionEquals(double comision)
	{
		try {
			VwAgenteDao _dao = getVwAgenteDao();
			VwAgente _result[] = _dao.findWhereComisionEquals(comision);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEmailEquals'
	 * 
	 * @param email
	 */
	public static void findWhereEmailEquals(String email)
	{
		try {
			VwAgenteDao _dao = getVwAgenteDao();
			VwAgente _result[] = _dao.findWhereEmailEquals(email);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSucursalEquals'
	 * 
	 * @param sucursal
	 */
	public static void findWhereSucursalEquals(String sucursal)
	{
		try {
			VwAgenteDao _dao = getVwAgenteDao();
			VwAgente _result[] = _dao.findWhereSucursalEquals(sucursal);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getVwAgenteDao'
	 * 
	 * @return VwAgenteDao
	 */
	public static VwAgenteDao getVwAgenteDao()
	{
		return VwAgenteDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(VwAgente dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getClave() );
		buf.append( ", " );
		buf.append( dto.getNombre() );
		buf.append( ", " );
		buf.append( dto.getTelefono() );
		buf.append( ", " );
		buf.append( dto.getCelular() );
		buf.append( ", " );
		buf.append( dto.getComision() );
		buf.append( ", " );
		buf.append( dto.getEmail() );
		buf.append( ", " );
		buf.append( dto.getSucursal() );
		System.out.println( buf.toString() );
	}

}
