/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.innovati.felipehernandez.invenenvios.clases.dao.VwArticulosDao;
import com.innovati.felipehernandez.invenenvios.clases.dto.VwArticulos;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.VwArticulosDaoException;
import com.innovati.felipehernandez.invenenvios.clases.factory.VwArticulosDaoFactory;

public class VwArticulosDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
   public static void main(String[] arg) throws Exception
   {
   	// Uncomment one of the lines below to test the generated code
   	
   	// findAll();
   	// findWhereClaveEquals("");
   	// findWhereNombreEquals("");
   	// findWhereUnidadPrimariaEquals("");
   	// findWherePrecio2Equals(0);
   	// findWherePrecio3Equals(0);
   	// findWherePrecio4Equals(0);
   	// findWherePrecio5Equals(0);
   	// findWhereTipoImpuestoEquals("");
   	// findWhereGrupoEquals("");
   	// findWhereTipoEquals("");
   	// findWhereStatusEquals("");
   	// findWhereUbicacionEquals("");
   	// findWhereMonedaEquals("");
   	// findWhereTiempoSurtidoEquals(0);
   	// findWherePedidoEquals(0);
   	// findWhereCostoPromedioEquals(0);
   	// findWhereUltimoCostoEquals(0);
   	// findWhereCostoReposicionEquals(0);
   	// findWhereExistenciaTotalEquals(0);
   	// findWhereActivoEquals("");
   	// findWherePrecio1Equals(0);
   	// findWhereClaseEquals("");
   	// findWhereCubicajeEquals(0);
   	// findWherePesoEquals(0);
   	// findWhereEquivalenciaEquals(0);
   }

	/**
	 * Method 'findAll'
	 * 
	 */
   public static void findAll()
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findAll();
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereClaveEquals'
	 * 
	 * @param clave
	 */
   public static void findWhereClaveEquals(String clave)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereClaveEquals(clave);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereNombreEquals'
	 * 
	 * @param nombre
	 */
   public static void findWhereNombreEquals(String nombre)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereNombreEquals(nombre);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereUnidadPrimariaEquals'
	 * 
	 * @param unidadPrimaria
	 */
   public static void findWhereUnidadPrimariaEquals(String unidadPrimaria)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereUnidadPrimariaEquals(unidadPrimaria);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWherePrecio2Equals'
	 * 
	 * @param precio2
	 */
   public static void findWherePrecio2Equals(double precio2)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWherePrecio2Equals(precio2);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWherePrecio3Equals'
	 * 
	 * @param precio3
	 */
   public static void findWherePrecio3Equals(double precio3)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWherePrecio3Equals(precio3);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWherePrecio4Equals'
	 * 
	 * @param precio4
	 */
   public static void findWherePrecio4Equals(double precio4)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWherePrecio4Equals(precio4);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWherePrecio5Equals'
	 * 
	 * @param precio5
	 */
   public static void findWherePrecio5Equals(double precio5)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWherePrecio5Equals(precio5);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereTipoImpuestoEquals'
	 * 
	 * @param tipoImpuesto
	 */
   public static void findWhereTipoImpuestoEquals(String tipoImpuesto)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereTipoImpuestoEquals(tipoImpuesto);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereGrupoEquals'
	 * 
	 * @param grupo
	 */
   public static void findWhereGrupoEquals(String grupo)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereGrupoEquals(grupo);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereTipoEquals'
	 * 
	 * @param tipo
	 */
   public static void findWhereTipoEquals(String tipo)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereTipoEquals(tipo);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereStatusEquals'
	 * 
	 * @param status
	 */
   public static void findWhereStatusEquals(String status)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereStatusEquals(status);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereUbicacionEquals'
	 * 
	 * @param ubicacion
	 */
   public static void findWhereUbicacionEquals(String ubicacion)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereUbicacionEquals(ubicacion);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereMonedaEquals'
	 * 
	 * @param moneda
	 */
   public static void findWhereMonedaEquals(String moneda)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereMonedaEquals(moneda);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereTiempoSurtidoEquals'
	 * 
	 * @param tiempoSurtido
	 */
   public static void findWhereTiempoSurtidoEquals(double tiempoSurtido)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereTiempoSurtidoEquals(tiempoSurtido);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWherePedidoEquals'
	 * 
	 * @param pedido
	 */
   public static void findWherePedidoEquals(double pedido)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWherePedidoEquals(pedido);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereCostoPromedioEquals'
	 * 
	 * @param costoPromedio
	 */
   public static void findWhereCostoPromedioEquals(double costoPromedio)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereCostoPromedioEquals(costoPromedio);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereUltimoCostoEquals'
	 * 
	 * @param ultimoCosto
	 */
   public static void findWhereUltimoCostoEquals(double ultimoCosto)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereUltimoCostoEquals(ultimoCosto);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereCostoReposicionEquals'
	 * 
	 * @param costoReposicion
	 */
   public static void findWhereCostoReposicionEquals(double costoReposicion)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereCostoReposicionEquals(costoReposicion);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereExistenciaTotalEquals'
	 * 
	 * @param existenciaTotal
	 */
   public static void findWhereExistenciaTotalEquals(double existenciaTotal)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereExistenciaTotalEquals(existenciaTotal);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereActivoEquals'
	 * 
	 * @param activo
	 */
   public static void findWhereActivoEquals(String activo)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereActivoEquals(activo);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWherePrecio1Equals'
	 * 
	 * @param precio1
	 */
   public static void findWherePrecio1Equals(double precio1)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWherePrecio1Equals(precio1);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereClaseEquals'
	 * 
	 * @param clase
	 */
   public static void findWhereClaseEquals(String clase)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereClaseEquals(clase);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereCubicajeEquals'
	 * 
	 * @param cubicaje
	 */
   public static void findWhereCubicajeEquals(double cubicaje)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereCubicajeEquals(cubicaje);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWherePesoEquals'
	 * 
	 * @param peso
	 */
   public static void findWherePesoEquals(double peso)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWherePesoEquals(peso);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'findWhereEquivalenciaEquals'
	 * 
	 * @param equivalencia
	 */
   public static void findWhereEquivalenciaEquals(double equivalencia)
   {
      try {
         VwArticulosDao _dao = getVwArticulosDao();
         VwArticulos _result[] = _dao.findWhereEquivalenciaEquals(equivalencia);
         for (int i=0; i<_result.length; i++ ) {
            display( _result[i] );
         }
      
      }
      catch (Exception _e) {
         _e.printStackTrace();
      }
   	
   }

	/**
	 * Method 'getVwArticulosDao'
	 * 
	 * @return VwArticulosDao
	 */
   public static VwArticulosDao getVwArticulosDao()
   {
      return VwArticulosDaoFactory.create();
   }

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
   public static void display(VwArticulos dto)
   {
      StringBuffer buf = new StringBuffer();
      buf.append( dto.getClave() );
      buf.append( ", " );
      buf.append( dto.getNombre() );
      buf.append( ", " );
      buf.append( dto.getUnidadPrimaria() );
      buf.append( ", " );
      buf.append( dto.getPrecio2() );
      buf.append( ", " );
      buf.append( dto.getPrecio3() );
      buf.append( ", " );
      buf.append( dto.getPrecio4() );
      buf.append( ", " );
      buf.append( dto.getPrecio5() );
      buf.append( ", " );
      buf.append( dto.getTipoImpuesto() );
      buf.append( ", " );
      buf.append( dto.getGrupo() );
      buf.append( ", " );
      buf.append( dto.getTipo() );
      buf.append( ", " );
      buf.append( dto.getStatus() );
      buf.append( ", " );
      buf.append( dto.getUbicacion() );
      buf.append( ", " );
      buf.append( dto.getMoneda() );
      buf.append( ", " );
      buf.append( dto.getTiempoSurtido() );
      buf.append( ", " );
      buf.append( dto.getPedido() );
      buf.append( ", " );
      buf.append( dto.getCostoPromedio() );
      buf.append( ", " );
      buf.append( dto.getUltimoCosto() );
      buf.append( ", " );
      buf.append( dto.getCostoReposicion() );
      buf.append( ", " );
      buf.append( dto.getExistenciaTotal() );
      buf.append( ", " );
      buf.append( dto.getActivo() );
      buf.append( ", " );
      buf.append( dto.getPrecio1() );
      buf.append( ", " );
      buf.append( dto.getClase() );
      buf.append( ", " );
      buf.append( dto.getCubicaje() );
      buf.append( ", " );
      buf.append( dto.getPeso() );
      buf.append( ", " );
      buf.append( dto.getEquivalencia() );
      System.out.println( buf.toString() );
   }

}
