/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.innovati.felipehernandez.invenenvios.clases.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.innovati.felipehernandez.invenenvios.clases.dao.VwDetallePedidoDao;
import com.innovati.felipehernandez.invenenvios.clases.dto.VwDetallePedido;
import com.innovati.felipehernandez.invenenvios.clases.exceptions.VwDetallePedidoDaoException;
import com.innovati.felipehernandez.invenenvios.clases.factory.VwDetallePedidoDaoFactory;

public class VwDetallePedidoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdPedidoEquals("");
		// findWhereIdDetallePedidoEquals("");
		// findWhereClaveArticuloEquals("");
		// findWhereNombreEquals("");
		// findWhereUnidadPrimariaEquals("");
		// findWhereCantidadEquals(0);
		// findWherePrecioEquals(0);
		// findWhereSubtotalEquals(0);
		// findWhereIvaEquals(0);
		// findWhereTotalEquals(0);
		// findWhereUltimaFechaActualizacionEquals(null);
		// findWhereUltimoUsuarioActualizacionEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdPedidoEquals'
	 * 
	 * @param idPedido
	 */
	public static void findWhereIdPedidoEquals(String idPedido)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereIdPedidoEquals(idPedido);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdDetallePedidoEquals'
	 * 
	 * @param idDetallePedido
	 */
	public static void findWhereIdDetallePedidoEquals(String idDetallePedido)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereIdDetallePedidoEquals(idDetallePedido);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereClaveArticuloEquals'
	 * 
	 * @param claveArticulo
	 */
	public static void findWhereClaveArticuloEquals(String claveArticulo)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereClaveArticuloEquals(claveArticulo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreEquals'
	 * 
	 * @param nombre
	 */
	public static void findWhereNombreEquals(String nombre)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereNombreEquals(nombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUnidadPrimariaEquals'
	 * 
	 * @param unidadPrimaria
	 */
	public static void findWhereUnidadPrimariaEquals(String unidadPrimaria)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereUnidadPrimariaEquals(unidadPrimaria);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCantidadEquals'
	 * 
	 * @param cantidad
	 */
	public static void findWhereCantidadEquals(double cantidad)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereCantidadEquals(cantidad);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePrecioEquals'
	 * 
	 * @param precio
	 */
	public static void findWherePrecioEquals(float precio)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWherePrecioEquals(precio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSubtotalEquals'
	 * 
	 * @param subtotal
	 */
	public static void findWhereSubtotalEquals(float subtotal)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereSubtotalEquals(subtotal);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIvaEquals'
	 * 
	 * @param iva
	 */
	public static void findWhereIvaEquals(float iva)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereIvaEquals(iva);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTotalEquals'
	 * 
	 * @param total
	 */
	public static void findWhereTotalEquals(float total)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereTotalEquals(total);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUltimaFechaActualizacionEquals'
	 * 
	 * @param ultimaFechaActualizacion
	 */
	public static void findWhereUltimaFechaActualizacionEquals(Date ultimaFechaActualizacion)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereUltimaFechaActualizacionEquals(ultimaFechaActualizacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUltimoUsuarioActualizacionEquals'
	 * 
	 * @param ultimoUsuarioActualizacion
	 */
	public static void findWhereUltimoUsuarioActualizacionEquals(String ultimoUsuarioActualizacion)
	{
		try {
			VwDetallePedidoDao _dao = getVwDetallePedidoDao();
			VwDetallePedido _result[] = _dao.findWhereUltimoUsuarioActualizacionEquals(ultimoUsuarioActualizacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getVwDetallePedidoDao'
	 * 
	 * @return VwDetallePedidoDao
	 */
	public static VwDetallePedidoDao getVwDetallePedidoDao()
	{
		return VwDetallePedidoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(VwDetallePedido dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdPedido() );
		buf.append( ", " );
		buf.append( dto.getIdDetallePedido() );
		buf.append( ", " );
		buf.append( dto.getClaveArticulo() );
		buf.append( ", " );
		buf.append( dto.getNombre() );
		buf.append( ", " );
		buf.append( dto.getUnidadPrimaria() );
		buf.append( ", " );
		buf.append( dto.getCantidad() );
		buf.append( ", " );
		buf.append( dto.getPrecio() );
		buf.append( ", " );
		buf.append( dto.getSubtotal() );
		buf.append( ", " );
		buf.append( dto.getIva() );
		buf.append( ", " );
		buf.append( dto.getTotal() );
		buf.append( ", " );
		buf.append( dto.getUltimaFechaActualizacion() );
		buf.append( ", " );
		buf.append( dto.getUltimoUsuarioActualizacion() );
		System.out.println( buf.toString() );
	}

}
