package com.innovati.felipehernandez.invenenvios.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.innovati.felipehernandez.invenenvios.database.Pedidos_I;
import com.innovati.felipehernandez.invenenvios.database.Usuarios_I;
import com.innovati.felipehernandez.invenenvios.database.VwAgente_I;
import com.innovati.felipehernandez.invenenvios.database.VwArticulos_I;
import com.innovati.felipehernandez.invenenvios.database.VwClientes_I;
import com.innovati.felipehernandez.invenenvios.database.VwDetallePedido_I;
import com.innovati.felipehernandez.invenenvios.database.VwUsuarios_I;
import com.innovati.felipehernandez.invenenvios.database.VwAbastecimientos_I;

import com.innovati.felipehernandez.invenenvios.database.Pedidos_IDao;
import com.innovati.felipehernandez.invenenvios.database.Usuarios_IDao;
import com.innovati.felipehernandez.invenenvios.database.VwAgente_IDao;
import com.innovati.felipehernandez.invenenvios.database.VwArticulos_IDao;
import com.innovati.felipehernandez.invenenvios.database.VwClientes_IDao;
import com.innovati.felipehernandez.invenenvios.database.VwDetallePedido_IDao;
import com.innovati.felipehernandez.invenenvios.database.VwUsuarios_IDao;
import com.innovati.felipehernandez.invenenvios.database.VwAbastecimientos_IDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pedidos_IDaoConfig;
    private final DaoConfig usuarios_IDaoConfig;
    private final DaoConfig vwAgente_IDaoConfig;
    private final DaoConfig vwArticulos_IDaoConfig;
    private final DaoConfig vwClientes_IDaoConfig;
    private final DaoConfig vwDetallePedido_IDaoConfig;
    private final DaoConfig vwUsuarios_IDaoConfig;
    private final DaoConfig vwAbastecimientos_IDaoConfig;

    private final Pedidos_IDao pedidos_IDao;
    private final Usuarios_IDao usuarios_IDao;
    private final VwAgente_IDao vwAgente_IDao;
    private final VwArticulos_IDao vwArticulos_IDao;
    private final VwClientes_IDao vwClientes_IDao;
    private final VwDetallePedido_IDao vwDetallePedido_IDao;
    private final VwUsuarios_IDao vwUsuarios_IDao;
    private final VwAbastecimientos_IDao vwAbastecimientos_IDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pedidos_IDaoConfig = daoConfigMap.get(Pedidos_IDao.class).clone();
        pedidos_IDaoConfig.initIdentityScope(type);

        usuarios_IDaoConfig = daoConfigMap.get(Usuarios_IDao.class).clone();
        usuarios_IDaoConfig.initIdentityScope(type);

        vwAgente_IDaoConfig = daoConfigMap.get(VwAgente_IDao.class).clone();
        vwAgente_IDaoConfig.initIdentityScope(type);

        vwArticulos_IDaoConfig = daoConfigMap.get(VwArticulos_IDao.class).clone();
        vwArticulos_IDaoConfig.initIdentityScope(type);

        vwClientes_IDaoConfig = daoConfigMap.get(VwClientes_IDao.class).clone();
        vwClientes_IDaoConfig.initIdentityScope(type);

        vwDetallePedido_IDaoConfig = daoConfigMap.get(VwDetallePedido_IDao.class).clone();
        vwDetallePedido_IDaoConfig.initIdentityScope(type);

        vwUsuarios_IDaoConfig = daoConfigMap.get(VwUsuarios_IDao.class).clone();
        vwUsuarios_IDaoConfig.initIdentityScope(type);

        vwAbastecimientos_IDaoConfig = daoConfigMap.get(VwAbastecimientos_IDao.class).clone();
        vwAbastecimientos_IDaoConfig.initIdentityScope(type);

        pedidos_IDao = new Pedidos_IDao(pedidos_IDaoConfig, this);
        usuarios_IDao = new Usuarios_IDao(usuarios_IDaoConfig, this);
        vwAgente_IDao = new VwAgente_IDao(vwAgente_IDaoConfig, this);
        vwArticulos_IDao = new VwArticulos_IDao(vwArticulos_IDaoConfig, this);
        vwClientes_IDao = new VwClientes_IDao(vwClientes_IDaoConfig, this);
        vwDetallePedido_IDao = new VwDetallePedido_IDao(vwDetallePedido_IDaoConfig, this);
        vwUsuarios_IDao = new VwUsuarios_IDao(vwUsuarios_IDaoConfig, this);
        vwAbastecimientos_IDao = new VwAbastecimientos_IDao(vwAbastecimientos_IDaoConfig, this);

        registerDao(Pedidos_I.class, pedidos_IDao);
        registerDao(Usuarios_I.class, usuarios_IDao);
        registerDao(VwAgente_I.class, vwAgente_IDao);
        registerDao(VwArticulos_I.class, vwArticulos_IDao);
        registerDao(VwClientes_I.class, vwClientes_IDao);
        registerDao(VwDetallePedido_I.class, vwDetallePedido_IDao);
        registerDao(VwUsuarios_I.class, vwUsuarios_IDao);
        registerDao(VwAbastecimientos_I.class, vwAbastecimientos_IDao);
    }
    
    public void clear() {
        pedidos_IDaoConfig.clearIdentityScope();
        usuarios_IDaoConfig.clearIdentityScope();
        vwAgente_IDaoConfig.clearIdentityScope();
        vwArticulos_IDaoConfig.clearIdentityScope();
        vwClientes_IDaoConfig.clearIdentityScope();
        vwDetallePedido_IDaoConfig.clearIdentityScope();
        vwUsuarios_IDaoConfig.clearIdentityScope();
        vwAbastecimientos_IDaoConfig.clearIdentityScope();
    }

    public Pedidos_IDao getPedidos_IDao() {
        return pedidos_IDao;
    }

    public Usuarios_IDao getUsuarios_IDao() {
        return usuarios_IDao;
    }

    public VwAgente_IDao getVwAgente_IDao() {
        return vwAgente_IDao;
    }

    public VwArticulos_IDao getVwArticulos_IDao() {
        return vwArticulos_IDao;
    }

    public VwClientes_IDao getVwClientes_IDao() {
        return vwClientes_IDao;
    }

    public VwDetallePedido_IDao getVwDetallePedido_IDao() {
        return vwDetallePedido_IDao;
    }

    public VwUsuarios_IDao getVwUsuarios_IDao() {
        return vwUsuarios_IDao;
    }

    public VwAbastecimientos_IDao getVwAbastecimientos_IDao() {
        return vwAbastecimientos_IDao;
    }

}
