package com.innovati.felipehernandez.invenenvios.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.innovati.felipehernandez.invenenvios.database.Pedidos;
import com.innovati.felipehernandez.invenenvios.database.DetallesPedidos;
import com.innovati.felipehernandez.invenenvios.database.Usuarios;
import com.innovati.felipehernandez.invenenvios.database.DetallesPedidos;
import com.innovati.felipehernandez.invenenvios.database.VwClientes;
import com.innovati.felipehernandez.invenenvios.database.VwArticulos;
import com.innovati.felipehernandez.invenenvios.database.VwUsuarios;
import com.innovati.felipehernandez.invenenvios.database.Pedidos;
import com.innovati.felipehernandez.invenenvios.database.VwAgente;

import com.innovati.felipehernandez.invenenvios.database.PedidosDao;
import com.innovati.felipehernandez.invenenvios.database.DetallesPedidosDao;
import com.innovati.felipehernandez.invenenvios.database.UsuariosDao;
import com.innovati.felipehernandez.invenenvios.database.DetallesPedidosDao;
import com.innovati.felipehernandez.invenenvios.database.VwClientesDao;
import com.innovati.felipehernandez.invenenvios.database.VwArticulosDao;
import com.innovati.felipehernandez.invenenvios.database.VwUsuariosDao;
import com.innovati.felipehernandez.invenenvios.database.PedidosDao;
import com.innovati.felipehernandez.invenenvios.database.VwAgenteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pedidosDaoConfig;
    private final DaoConfig detallesPedidosDaoConfig;
    private final DaoConfig usuariosDaoConfig;
    private final DaoConfig detallesPedidosDaoConfig;
    private final DaoConfig vwClientesDaoConfig;
    private final DaoConfig vwArticulosDaoConfig;
    private final DaoConfig vwUsuariosDaoConfig;
    private final DaoConfig pedidosDaoConfig;
    private final DaoConfig vwAgenteDaoConfig;

    private final PedidosDao pedidosDao;
    private final DetallesPedidosDao detallesPedidosDao;
    private final UsuariosDao usuariosDao;
    private final DetallesPedidosDao detallesPedidosDao;
    private final VwClientesDao vwClientesDao;
    private final VwArticulosDao vwArticulosDao;
    private final VwUsuariosDao vwUsuariosDao;
    private final PedidosDao pedidosDao;
    private final VwAgenteDao vwAgenteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pedidosDaoConfig = daoConfigMap.get(PedidosDao.class).clone();
        pedidosDaoConfig.initIdentityScope(type);

        detallesPedidosDaoConfig = daoConfigMap.get(DetallesPedidosDao.class).clone();
        detallesPedidosDaoConfig.initIdentityScope(type);

        usuariosDaoConfig = daoConfigMap.get(UsuariosDao.class).clone();
        usuariosDaoConfig.initIdentityScope(type);

        detallesPedidosDaoConfig = daoConfigMap.get(DetallesPedidosDao.class).clone();
        detallesPedidosDaoConfig.initIdentityScope(type);

        vwClientesDaoConfig = daoConfigMap.get(VwClientesDao.class).clone();
        vwClientesDaoConfig.initIdentityScope(type);

        vwArticulosDaoConfig = daoConfigMap.get(VwArticulosDao.class).clone();
        vwArticulosDaoConfig.initIdentityScope(type);

        vwUsuariosDaoConfig = daoConfigMap.get(VwUsuariosDao.class).clone();
        vwUsuariosDaoConfig.initIdentityScope(type);

        pedidosDao = new PedidosDao(pedidosDaoConfig, this);
        detallesPedidosDao = new DetallesPedidosDao(detallesPedidosDaoConfig, this);
        usuariosDao = new UsuariosDao(usuariosDaoConfig, this);
        detallesPedidosDao = new DetallesPedidosDao(detallesPedidosDaoConfig, this);
        vwClientesDao = new VwClientesDao(vwClientesDaoConfig, this);
        vwArticulosDao = new VwArticulosDao(vwArticulosDaoConfig, this);
        vwUsuariosDao = new VwUsuariosDao(vwUsuariosDaoConfig, this);
        pedidosDao = new PedidosDao(pedidosDaoConfig, this);
        vwAgenteDao = new VwAgenteDao(vwAgenteDaoConfig, this);

        registerDao(Pedidos.class, pedidosDao);
        registerDao(DetallesPedidos.class, detallesPedidosDao);
        registerDao(Usuarios.class, usuariosDao);
        registerDao(DetallesPedidos.class, detallesPedidosDao);
        registerDao(VwClientes.class, vwClientesDao);
        registerDao(VwArticulos.class, vwArticulosDao);
        registerDao(VwUsuarios.class, vwUsuariosDao);
        registerDao(Pedidos.class, pedidosDao);
        registerDao(VwAgente.class, vwAgenteDao);
    }
    
    public void clear() {
        pedidosDaoConfig.clearIdentityScope();
        detallesPedidosDaoConfig.clearIdentityScope();
        usuariosDaoConfig.clearIdentityScope();
        detallesPedidosDaoConfig.clearIdentityScope();
        vwClientesDaoConfig.clearIdentityScope();
        vwArticulosDaoConfig.clearIdentityScope();
        vwUsuariosDaoConfig.clearIdentityScope();
        pedidosDaoConfig.clearIdentityScope();
        vwAgenteDaoConfig.clearIdentityScope();
    }

    public PedidosDao getPedidosDao() {
        return pedidosDao;
    }

    public DetallesPedidosDao getDetallesPedidosDao() {
        return detallesPedidosDao;
    }

    public UsuariosDao getUsuariosDao() {
        return usuariosDao;
    }

    public DetallesPedidosDao getDetallesPedidosDao() {
        return detallesPedidosDao;
    }

    public VwClientesDao getVwClientesDao() {
        return vwClientesDao;
    }

    public VwArticulosDao getVwArticulosDao() {
        return vwArticulosDao;
    }

    public VwUsuariosDao getVwUsuariosDao() {
        return vwUsuariosDao;
    }

    public PedidosDao getPedidosDao() {
        return pedidosDao;
    }

    public VwAgenteDao getVwAgenteDao() {
        return vwAgenteDao;
    }

}
