package com.innovati.felipehernandez.invenenvios.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VW_ABASTECIMIENTOS__I".
*/
public class VwAbastecimientos_IDao extends AbstractDao<VwAbastecimientos_I, Void> {

    public static final String TABLENAME = "VW_ABASTECIMIENTOS__I";

    /**
     * Properties of entity VwAbastecimientos_I.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Nombre = new Property(0, String.class, "nombre", false, "NOMBRE");
        public final static Property Cantidad = new Property(1, float.class, "cantidad", false, "CANTIDAD");
        public final static Property UnidadPrimaria = new Property(2, String.class, "unidadPrimaria", false, "UNIDAD_PRIMARIA");
        public final static Property Estatus = new Property(3, short.class, "estatus", false, "ESTATUS");
    }


    public VwAbastecimientos_IDao(DaoConfig config) {
        super(config);
    }
    
    public VwAbastecimientos_IDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VW_ABASTECIMIENTOS__I\" (" + //
                "\"NOMBRE\" TEXT," + // 0: nombre
                "\"CANTIDAD\" REAL NOT NULL ," + // 1: cantidad
                "\"UNIDAD_PRIMARIA\" TEXT," + // 2: unidadPrimaria
                "\"ESTATUS\" INTEGER NOT NULL );"); // 3: estatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VW_ABASTECIMIENTOS__I\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VwAbastecimientos_I entity) {
        stmt.clearBindings();
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(1, nombre);
        }
        stmt.bindDouble(2, entity.getCantidad());
 
        String unidadPrimaria = entity.getUnidadPrimaria();
        if (unidadPrimaria != null) {
            stmt.bindString(3, unidadPrimaria);
        }
        stmt.bindLong(4, entity.getEstatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VwAbastecimientos_I entity) {
        stmt.clearBindings();
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(1, nombre);
        }
        stmt.bindDouble(2, entity.getCantidad());
 
        String unidadPrimaria = entity.getUnidadPrimaria();
        if (unidadPrimaria != null) {
            stmt.bindString(3, unidadPrimaria);
        }
        stmt.bindLong(4, entity.getEstatus());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public VwAbastecimientos_I readEntity(Cursor cursor, int offset) {
        VwAbastecimientos_I entity = new VwAbastecimientos_I( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // nombre
            cursor.getFloat(offset + 1), // cantidad
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // unidadPrimaria
            cursor.getShort(offset + 3) // estatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VwAbastecimientos_I entity, int offset) {
        entity.setNombre(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCantidad(cursor.getFloat(offset + 1));
        entity.setUnidadPrimaria(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEstatus(cursor.getShort(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(VwAbastecimientos_I entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(VwAbastecimientos_I entity) {
        return null;
    }

    @Override
    public boolean hasKey(VwAbastecimientos_I entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
