package com.innovati.felipehernandez.invenenvios.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VW_AGENTE__I".
*/
public class VwAgente_IDao extends AbstractDao<VwAgente_I, Long> {

    public static final String TABLENAME = "VW_AGENTE__I";

    /**
     * Properties of entity VwAgente_I.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property Clave = new Property(1, String.class, "clave", false, "CLAVE");
        public final static Property Nombre = new Property(2, String.class, "nombre", false, "NOMBRE");
        public final static Property Telefono = new Property(3, String.class, "telefono", false, "TELEFONO");
        public final static Property Celular = new Property(4, String.class, "celular", false, "CELULAR");
        public final static Property Comision = new Property(5, String.class, "comision", false, "COMISION");
        public final static Property Email = new Property(6, String.class, "email", false, "EMAIL");
        public final static Property Sucursal = new Property(7, String.class, "sucursal", false, "SUCURSAL");
    }


    public VwAgente_IDao(DaoConfig config) {
        super(config);
    }
    
    public VwAgente_IDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VW_AGENTE__I\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: Id
                "\"CLAVE\" TEXT," + // 1: clave
                "\"NOMBRE\" TEXT," + // 2: nombre
                "\"TELEFONO\" TEXT," + // 3: telefono
                "\"CELULAR\" TEXT," + // 4: celular
                "\"COMISION\" TEXT," + // 5: comision
                "\"EMAIL\" TEXT," + // 6: email
                "\"SUCURSAL\" TEXT);"); // 7: sucursal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VW_AGENTE__I\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VwAgente_I entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String clave = entity.getClave();
        if (clave != null) {
            stmt.bindString(2, clave);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(3, nombre);
        }
 
        String telefono = entity.getTelefono();
        if (telefono != null) {
            stmt.bindString(4, telefono);
        }
 
        String celular = entity.getCelular();
        if (celular != null) {
            stmt.bindString(5, celular);
        }
 
        String comision = entity.getComision();
        if (comision != null) {
            stmt.bindString(6, comision);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(7, email);
        }
 
        String sucursal = entity.getSucursal();
        if (sucursal != null) {
            stmt.bindString(8, sucursal);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VwAgente_I entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String clave = entity.getClave();
        if (clave != null) {
            stmt.bindString(2, clave);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(3, nombre);
        }
 
        String telefono = entity.getTelefono();
        if (telefono != null) {
            stmt.bindString(4, telefono);
        }
 
        String celular = entity.getCelular();
        if (celular != null) {
            stmt.bindString(5, celular);
        }
 
        String comision = entity.getComision();
        if (comision != null) {
            stmt.bindString(6, comision);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(7, email);
        }
 
        String sucursal = entity.getSucursal();
        if (sucursal != null) {
            stmt.bindString(8, sucursal);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VwAgente_I readEntity(Cursor cursor, int offset) {
        VwAgente_I entity = new VwAgente_I( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // clave
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nombre
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // telefono
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // celular
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // comision
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // email
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // sucursal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VwAgente_I entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClave(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNombre(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTelefono(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCelular(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setComision(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEmail(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSucursal(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VwAgente_I entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VwAgente_I entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VwAgente_I entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
